# Generated by Django 5.2.1 on 2025-06-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(default='Not Provided', max_length=250),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default='Not Provided', max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyname',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('website', models.CharField(default='N/A', max_length=200)),
                ('min_salary', models.CharField(default='0', max_length=200)),
                ('max_salary', models.CharField(default='0', max_length=200)),
                ('gender', models.CharField(default='Not Specified', max_length=200)),
                ('resume', models.FileField(upload_to='app/resume')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.detailsofjob')),
            ],
        ),
    ]
