# Generated by Django 5.2.1 on 2025-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_candidate_address_alter_candidate_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
