# Generated by Django 5.2.1 on 2025-06-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_applylist_max_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='experience',
            field=models.CharField(max_length=150),
        ),
    ]
