# Generated by Django 5.2.1 on 2025-06-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_applylist_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='app/resumes/'),
        ),
    ]
