# Generated by Django 5.2.1 on 2025-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_candidate_profile_pic_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
